# Generated by Django 4.1.7 on 2023-03-04 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('column_separator', models.CharField(choices=[(',', 'Comma'), (';', 'Semicolon'), ('|', 'Vertical Bar')], default=',', max_length=1)),
                ('string_character', models.CharField(choices=[('"', 'Double Quotes'), ("'", 'Single Quotes'), ('`', 'Backtick')], default='"', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data_type', models.CharField(choices=[('FULL_NAME', 'Full Name'), ('JOB', 'Job'), ('EMAIL', 'Email'), ('DOMAIN_NAME', 'Domain Name'), ('PHONE_NUMBER', 'Phone Number'), ('COMPANY_NAME', 'Company Name'), ('TEXT', 'Text'), ('INTEGER', 'Integer'), ('ADDRESS', 'Address'), ('DATE', 'Date')], max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('range_min', models.IntegerField(blank=True, null=True)),
                ('range_max', models.IntegerField(blank=True, null=True)),
                ('data_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.dataschema')),
            ],
        ),
    ]
