# Generated by Django 4.1.7 on 2023-03-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataschema',
            name='status',
            field=models.CharField(default='Not Started', max_length=20),
        ),
    ]
