# Generated by Django 4.1.7 on 2023-03-07 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_rename_datasets_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataschema',
            name='time_modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataset',
            name='file_reference',
            field=models.FileField(blank=True, null=True, upload_to='datasets/'),
        ),
    ]
